<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="css/style.css" rel="stylesheet">
        <title>Sistema de Votación</title>
    </head>
    <body>
        <h2 class="prueba">Bienvienido <?=$user->usuario?></h2>
        <a href="<?=$router->pathFor('logout')?>">Cerrar sesión</a>

        <script src="js/main.js"></script>
    </body>
</html>