<?php
/**
 * Created by PhpStorm.
 * User: johnf
 * Date: 14/10/2017
 * Time: 3:29 PM
 */
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="css/style.css" rel="stylesheet">
        <title>Inicio de sesión - Sistema de Votación</title>
    </head>
    <body>
        <h2>Inicio de sesión</h2>

        <script src="js/main.js"></script>
    </body>
</html>